// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: companyRecord.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_companyRecord_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_companyRecord_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_companyRecord_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_companyRecord_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_companyRecord_2eproto;
class Record;
struct RecordDefaultTypeInternal;
extern RecordDefaultTypeInternal _Record_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Record* Arena::CreateMaybeMessage<::Record>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Record final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Record) */ {
 public:
  inline Record() : Record(nullptr) {}
  ~Record() override;
  explicit PROTOBUF_CONSTEXPR Record(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Record(const Record& from);
  Record(Record&& from) noexcept
    : Record() {
    *this = ::std::move(from);
  }

  inline Record& operator=(const Record& from) {
    CopyFrom(from);
    return *this;
  }
  inline Record& operator=(Record&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Record& default_instance() {
    return *internal_default_instance();
  }
  static inline const Record* internal_default_instance() {
    return reinterpret_cast<const Record*>(
               &_Record_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Record& a, Record& b) {
    a.Swap(&b);
  }
  inline void Swap(Record* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Record* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Record* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Record>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Record& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Record& from) {
    Record::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Record* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Record";
  }
  protected:
  explicit Record(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCompanyNameFieldNumber = 2,
    kLegalAddressFieldNumber = 3,
    kOccupationFieldNumber = 4,
    kYearOfFoundationFieldNumber = 1,
    kForeignEconomicActivityFieldNumber = 5,
  };
  // required string companyName = 2;
  bool has_companyname() const;
  private:
  bool _internal_has_companyname() const;
  public:
  void clear_companyname();
  const std::string& companyname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_companyname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_companyname();
  PROTOBUF_NODISCARD std::string* release_companyname();
  void set_allocated_companyname(std::string* companyname);
  private:
  const std::string& _internal_companyname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_companyname(const std::string& value);
  std::string* _internal_mutable_companyname();
  public:

  // required string legalAddress = 3;
  bool has_legaladdress() const;
  private:
  bool _internal_has_legaladdress() const;
  public:
  void clear_legaladdress();
  const std::string& legaladdress() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_legaladdress(ArgT0&& arg0, ArgT... args);
  std::string* mutable_legaladdress();
  PROTOBUF_NODISCARD std::string* release_legaladdress();
  void set_allocated_legaladdress(std::string* legaladdress);
  private:
  const std::string& _internal_legaladdress() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_legaladdress(const std::string& value);
  std::string* _internal_mutable_legaladdress();
  public:

  // optional string occupation = 4;
  bool has_occupation() const;
  private:
  bool _internal_has_occupation() const;
  public:
  void clear_occupation();
  const std::string& occupation() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_occupation(ArgT0&& arg0, ArgT... args);
  std::string* mutable_occupation();
  PROTOBUF_NODISCARD std::string* release_occupation();
  void set_allocated_occupation(std::string* occupation);
  private:
  const std::string& _internal_occupation() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_occupation(const std::string& value);
  std::string* _internal_mutable_occupation();
  public:

  // required int32 yearOfFoundation = 1;
  bool has_yearoffoundation() const;
  private:
  bool _internal_has_yearoffoundation() const;
  public:
  void clear_yearoffoundation();
  int32_t yearoffoundation() const;
  void set_yearoffoundation(int32_t value);
  private:
  int32_t _internal_yearoffoundation() const;
  void _internal_set_yearoffoundation(int32_t value);
  public:

  // optional bool foreignEconomicActivity = 5;
  bool has_foreigneconomicactivity() const;
  private:
  bool _internal_has_foreigneconomicactivity() const;
  public:
  void clear_foreigneconomicactivity();
  bool foreigneconomicactivity() const;
  void set_foreigneconomicactivity(bool value);
  private:
  bool _internal_foreigneconomicactivity() const;
  void _internal_set_foreigneconomicactivity(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Record)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr companyname_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr legaladdress_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr occupation_;
    int32_t yearoffoundation_;
    bool foreigneconomicactivity_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_companyRecord_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Record

// required int32 yearOfFoundation = 1;
inline bool Record::_internal_has_yearoffoundation() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Record::has_yearoffoundation() const {
  return _internal_has_yearoffoundation();
}
inline void Record::clear_yearoffoundation() {
  _impl_.yearoffoundation_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline int32_t Record::_internal_yearoffoundation() const {
  return _impl_.yearoffoundation_;
}
inline int32_t Record::yearoffoundation() const {
  // @@protoc_insertion_point(field_get:Record.yearOfFoundation)
  return _internal_yearoffoundation();
}
inline void Record::_internal_set_yearoffoundation(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.yearoffoundation_ = value;
}
inline void Record::set_yearoffoundation(int32_t value) {
  _internal_set_yearoffoundation(value);
  // @@protoc_insertion_point(field_set:Record.yearOfFoundation)
}

// required string companyName = 2;
inline bool Record::_internal_has_companyname() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Record::has_companyname() const {
  return _internal_has_companyname();
}
inline void Record::clear_companyname() {
  _impl_.companyname_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Record::companyname() const {
  // @@protoc_insertion_point(field_get:Record.companyName)
  return _internal_companyname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Record::set_companyname(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.companyname_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Record.companyName)
}
inline std::string* Record::mutable_companyname() {
  std::string* _s = _internal_mutable_companyname();
  // @@protoc_insertion_point(field_mutable:Record.companyName)
  return _s;
}
inline const std::string& Record::_internal_companyname() const {
  return _impl_.companyname_.Get();
}
inline void Record::_internal_set_companyname(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.companyname_.Set(value, GetArenaForAllocation());
}
inline std::string* Record::_internal_mutable_companyname() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.companyname_.Mutable(GetArenaForAllocation());
}
inline std::string* Record::release_companyname() {
  // @@protoc_insertion_point(field_release:Record.companyName)
  if (!_internal_has_companyname()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.companyname_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.companyname_.IsDefault()) {
    _impl_.companyname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Record::set_allocated_companyname(std::string* companyname) {
  if (companyname != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.companyname_.SetAllocated(companyname, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.companyname_.IsDefault()) {
    _impl_.companyname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Record.companyName)
}

// required string legalAddress = 3;
inline bool Record::_internal_has_legaladdress() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Record::has_legaladdress() const {
  return _internal_has_legaladdress();
}
inline void Record::clear_legaladdress() {
  _impl_.legaladdress_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Record::legaladdress() const {
  // @@protoc_insertion_point(field_get:Record.legalAddress)
  return _internal_legaladdress();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Record::set_legaladdress(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.legaladdress_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Record.legalAddress)
}
inline std::string* Record::mutable_legaladdress() {
  std::string* _s = _internal_mutable_legaladdress();
  // @@protoc_insertion_point(field_mutable:Record.legalAddress)
  return _s;
}
inline const std::string& Record::_internal_legaladdress() const {
  return _impl_.legaladdress_.Get();
}
inline void Record::_internal_set_legaladdress(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.legaladdress_.Set(value, GetArenaForAllocation());
}
inline std::string* Record::_internal_mutable_legaladdress() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.legaladdress_.Mutable(GetArenaForAllocation());
}
inline std::string* Record::release_legaladdress() {
  // @@protoc_insertion_point(field_release:Record.legalAddress)
  if (!_internal_has_legaladdress()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.legaladdress_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.legaladdress_.IsDefault()) {
    _impl_.legaladdress_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Record::set_allocated_legaladdress(std::string* legaladdress) {
  if (legaladdress != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.legaladdress_.SetAllocated(legaladdress, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.legaladdress_.IsDefault()) {
    _impl_.legaladdress_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Record.legalAddress)
}

// optional string occupation = 4;
inline bool Record::_internal_has_occupation() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Record::has_occupation() const {
  return _internal_has_occupation();
}
inline void Record::clear_occupation() {
  _impl_.occupation_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& Record::occupation() const {
  // @@protoc_insertion_point(field_get:Record.occupation)
  return _internal_occupation();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Record::set_occupation(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000004u;
 _impl_.occupation_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Record.occupation)
}
inline std::string* Record::mutable_occupation() {
  std::string* _s = _internal_mutable_occupation();
  // @@protoc_insertion_point(field_mutable:Record.occupation)
  return _s;
}
inline const std::string& Record::_internal_occupation() const {
  return _impl_.occupation_.Get();
}
inline void Record::_internal_set_occupation(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.occupation_.Set(value, GetArenaForAllocation());
}
inline std::string* Record::_internal_mutable_occupation() {
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.occupation_.Mutable(GetArenaForAllocation());
}
inline std::string* Record::release_occupation() {
  // @@protoc_insertion_point(field_release:Record.occupation)
  if (!_internal_has_occupation()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* p = _impl_.occupation_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.occupation_.IsDefault()) {
    _impl_.occupation_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Record::set_allocated_occupation(std::string* occupation) {
  if (occupation != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.occupation_.SetAllocated(occupation, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.occupation_.IsDefault()) {
    _impl_.occupation_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Record.occupation)
}

// optional bool foreignEconomicActivity = 5;
inline bool Record::_internal_has_foreigneconomicactivity() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Record::has_foreigneconomicactivity() const {
  return _internal_has_foreigneconomicactivity();
}
inline void Record::clear_foreigneconomicactivity() {
  _impl_.foreigneconomicactivity_ = false;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline bool Record::_internal_foreigneconomicactivity() const {
  return _impl_.foreigneconomicactivity_;
}
inline bool Record::foreigneconomicactivity() const {
  // @@protoc_insertion_point(field_get:Record.foreignEconomicActivity)
  return _internal_foreigneconomicactivity();
}
inline void Record::_internal_set_foreigneconomicactivity(bool value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.foreigneconomicactivity_ = value;
}
inline void Record::set_foreigneconomicactivity(bool value) {
  _internal_set_foreigneconomicactivity(value);
  // @@protoc_insertion_point(field_set:Record.foreignEconomicActivity)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_companyRecord_2eproto
